# Generated by Django 6.0.3 on 2026-04-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_assignment_assignment_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='course',
            name='subcategory',
            field=models.ManyToManyField(related_name='courses', to='course_app.subcategory'),
        ),
    ]
